//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationApiChrysallis
{
    using System;
    using System.Collections.Generic;
    
    public partial class mensajes
    {
        public int id { get; set; }
        public int id_socio { get; set; }
        public int id_evento { get; set; }
        public byte[] mensaje { get; set; }
        public System.DateTime fecha { get; set; }
    
        public virtual socios socios { get; set; }
        public virtual eventos eventos { get; set; }
    }
}
