//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationApiChrysallis
{
    using System;
    using System.Collections.Generic;
    
    public partial class socios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public socios()
        {
            this.asistir = new HashSet<asistir>();
            this.mensajes = new HashSet<mensajes>();
        }
    
        public int id { get; set; }
        public string dni { get; set; }
        public string telefono { get; set; }
        public string nombre { get; set; }
        public string apellidos { get; set; }
        public bool activo { get; set; }
        public string mail { get; set; }
        public string password { get; set; }
        public bool administrador { get; set; }
        public string idiomaDefecto { get; set; }
        public bool estatal { get; set; }
        public string imagenUsuario { get; set; }
        public Nullable<int> id_comunidad { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<asistir> asistir { get; set; }
        public virtual comunidades comunidades { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mensajes> mensajes { get; set; }
    }
}
